app = "fiacha-staging"
primary_region = "lhr"  # London - change to your preferred region

[build]

[env]
  NODE_ENV = "production"
  NEXT_PUBLIC_API_URL = "https://fiacha-staging.fly.dev"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

  [[http_service.checks]]
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    timeout = "5s"
    path = "/api/healthz"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512
